# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: true
  branches:
    include:
    - master

pool:
  name: Default
  demands: 
    - Agent.Name -equals Dheerajs-MacBook-Pro 

variables:
- group: state-data

stages:
- stage: build_and_test
  jobs:
  - job: "show_subscription_and_show_current_dir"
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'tacowagon-dev'
        addSpnToEnvironment: true # Mandatory to get the idToken variable
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # 1. Access the token directly in this script
          echo "The federated token is: $idToken"

          # 2. (Optional) Export it for tools like Terraform
          export ARM_OIDC_TOKEN=$idToken
          export ARM_USE_OIDC=true

          # 3. (Optional) Save it as a pipeline variable for later steps in the same job
          echo "##vso[task.setvariable variable=MY_OIDC_TOKEN]$idToken"
  
- stage: Validation
  jobs:
  - job: Terraform_Validate
    pool:
      name: Default # Ensure your local Mac agent is in this pool
      demands: 
         - Agent.Name -equals Dheerajs-MacBook-Pro
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraform_version)

    - bash: |
        cd /Users/dheerajmaganti/Library/Mobile Documents/com~apple~CloudDocs/Documents/aks-three-tier/infra/
        terraform fmt -check
        terraform init -backend=false
        terraform validate
      workingDirectory: $(working_directory)
      displayName: 'Terraform Format and Validate'